enum ExpensesCategory {
  FOOD = 1,
  GIFTS,
  MEDICAL,
  EDUCATION,
  RESTAURANTS,
  UTILITIES,
  FUEL_AND_CAR,
  CAFE_AND_BARS,
  SNACKS_AND_WATER,
  ENTERTAINMENT,
  HYGIENE,
  CLOTHES_AND_WEARABLES,
  INVESTING_AND_FEES,
  MARKETS,
  BOOKS,
  SOFTWARE_AND_HARDWARE,
  ALIEXPRESS,
  ATM,
}

export default ExpensesCategory;
